version: '3.8'

networks:
  npp:

services:
  snginx:
    image: nginx:1.21.5
    container_name: cnginx
    ports:
      - "8080:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sphp
      - spostgres
    networks:
      - npp

  sphp:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: cphp
    volumes:
      - .:/var/www/code/
    command: composer install
    ports:
      - "9000:9000"
    networks:
      - npp

  spostgres:
    image: postgres:14.1
    container_name: cpostgres
    ports:
      - "6432:5432"
    volumes:
      - ../pgsql:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - npp